language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - nightly
  - hhvm

matrix:
    allow_failures:
        - php: nightly
        - php: hhvm

before_install:
  - sudo apt-get update
  - sudo apt-get -y --reinstall install imagemagick

before_script:
  - composer self-update
  - composer install --dev

script: phpunit
